language: ruby
before_install:
  - gem update bundler
  - bundle -v
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
notifications:
  recipients:
    - remy@rymai.me
