script: "bundle exec rake --trace 2>&1"
rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - ree
  - rbx
  - jruby
# env:
#   - CI=true
# Specify the recipients for email notification
notifications:
  recipients:
    - rymai@rymai.me
